# Generated by Django 2.1.1 on 2018-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='run_duration',
        ),
        migrations.AddField(
            model_name='run',
            name='run_uuid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
